---
- name: Configure alacritty
  block:
    - name: Ensure config folder exists
      ansible.builtin.file:
        path: "{{ alacritty_config_dir }}"
        state: directory
        mode: "0750"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Add alacritty config file
      ansible.builtin.template:
        src: "{{ role_path }}/templates/alacritty.toml.j2"
        dest: "{{ alacritty_config_dir }}/alacritty.toml"
        mode: "0600"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
