---
- name: Ensure alacritty is installed
  block:
    - name: Get installed alacritty version
      ansible.builtin.command:
        cmd: "alacritty --version"
      environment:
        PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
      ignore_errors: true
      changed_when: false
      failed_when: false
      register: alacritty_version_cmd

    - name: Extract only the version into a variable
      ansible.builtin.set_fact:
        alacritty_installed_version: "{{ alacritty_version_cmd.stdout | regex_replace('^.*?([\\d\\.]{2,}).*$', '\\1') }}"

    - name: Debug installed alacritty version
      ansible.builtin.debug:
        var: alacritty_installed_version

    - name: Force install if the version numbers do not match
      ansible.builtin.set_fact:
        alacritty_reinstall_from_source: true
      when:
        - alacritty_installed_version is defined
        - alacritty_installed_version != alacritty_version

    - name: Install alacritty from source
      when: alacritty_installed_version is not defined or alacritty_reinstall_from_source
      block:
        - name: Download alacritty
          ansible.builtin.get_url:
            url: "https://github.com/alacritty/alacritty/archive/refs/tags/v{{ alacritty_version }}.tar.gz"
            dest: "{{ alacritty_build_dir }}/alacritty-{{ alacritty_version }}.tar.gz"
            mode: "0600"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"

        - name: Extract archive
          ansible.builtin.unarchive:
            src: "{{ alacritty_build_dir }}/alacritty-{{ alacritty_version }}.tar.gz"
            dest: "{{ alacritty_build_dir }}/"
            remote_src: true

        - name: Build alacritty
          ansible.builtin.command:
            cmd: "cargo build --release"
            chdir: "{{ alacritty_build_dir }}/alacritty-{{ alacritty_version }}"
          environment:
            PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
          changed_when: true

        - name: Install alacritty
          ansible.builtin.command:
            cmd: "cargo install --path {{ alacritty_build_dir }}/alacritty-{{ alacritty_version }}/alacritty"
          environment:
            PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
          changed_when: true

        - name: Remove build directory
          ansible.builtin.file:
            path: "{{ alacritty_build_dir }}/alacritty-{{ alacritty_version }}"
            state: absent

        - name: Remove archive
          ansible.builtin.file:
            path: "{{ alacritty_build_dir }}/alacritty-{{ alacritty_version }}.tar.gz"
            state: absent
