---
- name: Ensure alacritty is installed
  block:
    - name: Import installed alacritty version check
      ansible.builtin.include_tasks: noauto_check_installed_version.yml
      when: alacritty_installed_version is not defined

    - name: Force install if the version numbers do not match
      ansible.builtin.set_fact:
        alacritty_force_install: true
      when:
        - alacritty_installed_version is defined
        - alacritty_installed_version != alacritty_version

    - name: Install alacritty from source
      when: alacritty_installed_version is not defined or alacritty_force_install
      block:
        - name: Uninstall current alacritty installation
          ansible.builtin.include_tasks: noauto_uninstall.yml

        - name: Download alacritty
          ansible.builtin.get_url:
            url: "{{ alacritty_download_url }}"
            dest: "{{ alacritty_download_dir }}/alacritty-{{ alacritty_version }}.tar.gz"
            mode: "0600"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"

        - name: Extract archive
          ansible.builtin.unarchive:
            src: "{{ alacritty_download_dir }}/alacritty-{{ alacritty_version }}.tar.gz"
            dest: "{{ alacritty_download_dir }}/"
            remote_src: true

        - name: Build alacritty
          ansible.builtin.command:
            cmd: "cargo build --release"
            chdir: "{{ alacritty_download_dir }}/alacritty-{{ alacritty_version }}"
          environment:
            PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
          changed_when: true

        - name: Install alacritty
          ansible.builtin.command:
            cmd: "cargo install --path {{ alacritty_download_dir }}/alacritty-{{ alacritty_version }}/alacritty"
          environment:
            PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
          changed_when: true

        - name: Remove build directory
          ansible.builtin.file:
            path: "{{ alacritty_download_dir }}/alacritty-{{ alacritty_version }}"
            state: absent

        - name: Remove archive
          ansible.builtin.file:
            path: "{{ alacritty_download_dir }}/alacritty-{{ alacritty_version }}.tar.gz"
            state: absent
